// GENERATED by scripts/gen-image-meta.mjs — do not edit by hand.
// Re-run after adding or replacing anything in public/images.

export interface ImageMeta {
  w: number;
  h: number;
}

export const IMAGE_META: Record<string, ImageMeta> = {
  '/images/commuter-benefits/carousel-2.png': { w: 1903, h: 977 },
  '/images/commuter-benefits/carousel-3.png': { w: 1911, h: 982 },
  '/images/commuter-benefits/carousel-4.png': { w: 1907, h: 981 },
  '/images/commuter-benefits/problem-overview.png': { w: 1907, h: 968 },
  '/images/commuter-benefits/solution-final.png': { w: 1912, h: 967 },
  '/images/commuter-benefits/wireframe-1.svg': { w: 960, h: 540 },
  '/images/crew/josh.jpg': { w: 938, h: 989 },
  '/images/crew/noodles.jpg': { w: 508, h: 989 },
  '/images/crew/squash.jpg': { w: 741, h: 989 },
  '/images/fleet-card/problem-overview.png': { w: 1917, h: 937 },
  '/images/fleet-card/solution-1.png': { w: 1913, h: 902 },
  '/images/fleet-card/solution-2.png': { w: 1912, h: 852 },
  '/images/fleet-card/solution-3.png': { w: 1912, h: 957 },
  '/images/fleet-card/solution-4.png': { w: 1913, h: 766 },
  '/images/fleet-card/wireframe-1.svg': { w: 960, h: 540 },
  '/images/groundbase/problem-overview.png': { w: 1782, h: 882 },
  '/images/groundbase/solution-1.png': { w: 1898, h: 977 },
  '/images/groundbase/solution-2.png': { w: 1897, h: 980 },
  '/images/groundbase/solution-3.png': { w: 1645, h: 820 },
  '/images/groundbase/wireframe-1.svg': { w: 960, h: 540 },
  '/images/identity-profiles/problem-overview.png': { w: 997, h: 767 },
  '/images/identity-profiles/solution-1.png': { w: 1208, h: 318 },
  '/images/identity-profiles/solution-2.png': { w: 1021, h: 370 },
  '/images/identity-profiles/solution-3.png': { w: 752, h: 817 },
  '/images/identity-profiles/solution-4.png': { w: 1032, h: 581 },
  '/images/identity-profiles/wireframe-1.svg': { w: 960, h: 540 },
  '/images/jobwatch/ashby.png': { w: 192, h: 192 },
  '/images/jobwatch/breezy.png': { w: 256, h: 256 },
  '/images/jobwatch/greenhouse.png': { w: 256, h: 256 },
  '/images/jobwatch/lever.png': { w: 48, h: 48 },
  '/images/jobwatch/problem-overview.png': { w: 1920, h: 1200 },
  '/images/jobwatch/rippling.png': { w: 180, h: 180 },
  '/images/jobwatch/smartrecruiters.png': { w: 192, h: 192 },
  '/images/jobwatch/solution-1.png': { w: 1920, h: 1200 },
  '/images/jobwatch/solution-2.png': { w: 1920, h: 1200 },
  '/images/jobwatch/solution-3.png': { w: 1920, h: 1200 },
  '/images/jobwatch/solution-4.png': { w: 1920, h: 1200 },
  '/images/jobwatch/solution-5.png': { w: 1920, h: 1200 },
  '/images/jobwatch/wireframe-1.svg': { w: 960, h: 540 },
  '/images/jobwatch/workday.png': { w: 32, h: 32 },
  '/images/security-data-lake/problem-overview.png': { w: 907, h: 659 },
  '/images/security-data-lake/solution-1.png': { w: 946, h: 895 },
  '/images/security-data-lake/solution-2.png': { w: 1191, h: 470 },
  '/images/security-data-lake/solution-3.png': { w: 987, h: 517 },
  '/images/security-data-lake/solution-4.png': { w: 1065, h: 496 },
  '/images/security-data-lake/wireframe-1.svg': { w: 960, h: 540 },
  '/images/shared/Jc3zaUXnuoCQadUYGeG46Woayw.png': { w: 64, h: 64 },
  '/images/shared/cta-banner.png': { w: 1024, h: 434 },
  '/images/shared/debate-face-1.png': { w: 245, h: 246 },
  '/images/shared/debate-face-2.png': { w: 246, h: 248 },
  '/images/shared/debate-face-3.png': { w: 251, h: 250 },
  '/images/shared/debate-face-4.png': { w: 245, h: 245 },
  '/images/shared/edenred-hero.png': { w: 800, h: 513 },
  '/images/shared/jAxsIlnyGdzuKUigfqgaBZMuZ2o.png': { w: 64, h: 64 },
  '/images/shared/key-decision-banner.png': { w: 715, h: 300 },
  '/images/shared/red-canary-hero.png': { w: 1007, h: 1080 },
  '/images/status-checks/carousel-1.png': { w: 1186, h: 287 },
  '/images/status-checks/carousel-2.png': { w: 1102, h: 646 },
  '/images/status-checks/wireframe-1.svg': { w: 960, h: 540 },
  '/images/unified-onboarding/problem-overview.png': { w: 1227, h: 742 },
  '/images/unified-onboarding/solution-1.png': { w: 1038, h: 445 },
  '/images/unified-onboarding/solution-2.png': { w: 1042, h: 732 },
  '/images/unified-onboarding/solution-3.png': { w: 1024, h: 535 },
  '/images/unified-onboarding/wireframe-1.svg': { w: 960, h: 540 },
};

/** Intrinsic dimensions for a public/images path. Falls back to 16:9 for unknown files. */
export function imageMeta(src: string): ImageMeta {
  return IMAGE_META[src] ?? { w: 1600, h: 900 };
}
